apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Client
  template:
    metadata:
      labels:
        app: Client
    spec:
      containers:
      - name: clientrepos
        image: truyumcr.azurecr.io/clientrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Client